NumberGuessingGame: NumberGuessingGame.o
	g++ -std=c++11 -g -Wall NumberGuessingGame.o -o NumberGuessingGame

NumberGuessingGame.o: NumberGuessingGame.cpp
	g++ -std=c++11 -g -Wall -c NumberGuessingGame.cpp

clean:
	rm *.o NumberGuessingGame

