FibonacciAgain: FibonacciAgain.o
	g++ -std=c++11 -g -Wall FibonacciAgain.o -o FibonacciAgain

FibonacciAgain.o: FibonacciAgain.cpp
	g++ -std=c++11 -g -Wall -c FibonacciAgain.cpp

clean:
	rm *.o FibonacciAgian

