WordGuessingGame: WordGuessingGame.o
	g++ -std=c++11 -g -Wall WordGuessingGame.o -o WordGuessingGame

WordGuessingGame.o: WordGuessingGame.cpp
	g++ -std=c++11 -g -Wall -c WordGuessingGame.cpp

clean:
	rm *.o WordGuessingGame

